### ISSUE TITLE
Some png became green

### ISSUE THREAD

**Issue by player-guest** [windyfairy/gitadora-textool#3]
The game I try to unpack is gitadora matixx, and some of the png is all green.
I think that is a placeholder image .
If I unpack and repack without any modify, this image show green in game too.

![コメント 2019-09-23 145549](https://user-images.githubusercontent.com/52330000/65404180-7843d600-de12-11e9-9435-119800cf6065.png)
Here is the extracted file 

![コメント 2019-09-23 144907](https://user-images.githubusercontent.com/52330000/65404305-f7390e80-de12-11e9-9c5e-2c6e9cd39ce7.png)
Here is what it looks like in game

I try to make a fully transparent png to replace the green png but no, in game is does remove the green image but also not showing the text should show at there.

**Comment by windyfairy** [comment]
I think the green image is correct. However I think a flag is not getting set properly in the header of the texture. A RGBA texture has 0x2c set to 3 when it wants to use regular transparency, but these have 0x2c set to 1 or 2 it seems.

I'll try to get it fixed later.

**Comment by windyfairy** [comment]
I added a fix but it requires using `--no-split`. It will output an addition metadata file, `metadata-format.xml`, and use that to set the specific byte. It might be a bit buggy though since I haven't tested it thoroughly yet.

If you want to modify images within the spritesheets, you can modify metadata.xml to point to a different external file instead of the spritesheet and update the X/Y values to be 0,0 (or whatever point in the replacement spritesheet the image would be).

Please let me know if this fixes the issue.

**Comment by player-guest** [comment]
Great, this solve the issue.
Will you fix this in split mode? Or I can generate the _metadata.xml by myself.

**Comment by windyfairy** [comment]
@player-guest I tried implementing it for split mode. Please try it out.

**Comment by player-guest** [comment]
In split mode the _metadata-format.xml is generated but still appear green in game after repack.
I try to print the formatTypeList and it output the right type for those files.

**Comment by windyfairy** [comment]
I guess your only option is going to be to use `--no-split` mode for those files then. Sorry. :(
